name: "Vowel Frequency Analyzer"
description: "custom action to analyse vowels frequncy"

inputs:
  file:
    description: "Path to the text file to analyze (e.g. data.txt)"
    required: true

runs:
  using: "docker"
  image: "ghcr.io/tengjiyun/vowel-frequency-analyzer:latest"
  entrypoint:
    - "/bin/bash"
    - "/app/.github/scripts/entrypoint.sh"
  env:
    FILE: "${{ inputs.file }}"
   
