name: Collaborative Workflow

on:
  push:
    branches: 
     - main

jobs:
    update_html_and_readme:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update Leader Page
        if: ${{ github.actor == 'TeamLeaderUsername' }}
        run: |
          sed -i "/<\/body>/i <p>Updated by tengjiyun }} on $(date)<\/p>/" leader.html
      - name: Update Member 1 Page
        if: ${{ github.actor == 'member1_username' }}
        run: |
          sed -i "/<\/body>/i <p>Updated by ${{ github.actor }} on $(date)<\/p>/" member1.html
      - name: Update Member 2 Page
        if: ${{ github.actor == 'member2_username' }}
        run: |
          sed -i "/<\/body>/i <p>Updated by ${{ github.actor }} on $(date)<\/p>/" member2.html
      - name: Update README.md               
        run: |                                
          echo "### Updated by ${{ github.actor }} on $(date '+%Y-%m-%d %H:%M:%S') [Commit: $(git rev-parse --short HEAD)]" >> README.md  # ③

      - name: Commit and Push Changes         
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md index.html
          git commit -m "ci: log update in README by ${{ github.actor }}" || echo "No changes to commit"
          git push
